language: perl

perl:
  - "5.24"
  - "5.26"

install:
  - maint/travis-install-alienautotools
  - cpanm Test2::V0 FFI::Platypus Path::Tiny Alien::Autotools IPC::System::Simple

script:
  - ./maint/regen
  - ./maint/autohell autoreconf -vfi
  - ./configure
  - prove -v t

env:
  global:
    - ALIEN_BASE_NO_ABMB=1
