#!/bin/bash -x

set -euo pipefail
IFS=$'\n\t'

rm -rf /tmp/Alien-Autotools

cpanm -n Dist::Zilla

git clone --depth 2 https://github.com/plicease/Alien-Autotools.git /tmp/Alien-Autotools
cd /tmp/Alien-Autotools
dzil authordeps --missing | cpanm -n
dzil listdeps   --missing | cpanm -n
dzil install --install-command 'cpanm -n -v .'

